/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package LMSMiniProject.TablePanels;

import LMSMiniProject.DbConnection;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Vijay Srinivas K
 */
public class BorrowPanel extends javax.swing.JPanel {
    private Connection con;
    private Statement st;
    private PreparedStatement ps;
    private ResultSet rs;
    /**
     * Creates new form LibraryPanel
     */
    public BorrowPanel() {
        initComponents();
        
        try {
            con = DbConnection.getConnection();
        }
        catch (SQLException | ClassNotFoundException ignore) {
        }
        //setPreferredSize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panes = new javax.swing.JTabbedPane();
        Enter = new javax.swing.JPanel();
        Enter1 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        enterLibId = new javax.swing.JTextField();
        InsertButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lib_det = new javax.swing.JPanel();
        Create = new javax.swing.JPanel();
        Create1 = new javax.swing.JPanel();
        InsertButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lib_det1 = new javax.swing.JPanel();
        InsertButton2 = new javax.swing.JButton();
        Create2 = new javax.swing.JPanel();
        Create3 = new javax.swing.JPanel();
        InsertButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        LibraryId4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        LibraryName3 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        LibraryName4 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        LibraryId5 = new javax.swing.JTextField();
        Enter2 = new javax.swing.JPanel();
        Enter3 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        enterLibId1 = new javax.swing.JTextField();
        InsertButton6 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        lib_det2 = new javax.swing.JPanel();
        Enter4 = new javax.swing.JPanel();
        Enter5 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        enterLibId2 = new javax.swing.JTextField();
        InsertButton7 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Enter6 = new javax.swing.JPanel();
        Enter7 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        enterLibId3 = new javax.swing.JTextField();
        InsertButton8 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));

        Panes.setBackground(new java.awt.Color(102, 153, 255));
        Panes.setPreferredSize(new java.awt.Dimension(500, 500));

        Enter.setBackground(new java.awt.Color(153, 255, 255));

        Enter1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel27.setText("Book Name : ");

        enterLibId.setColumns(10);
        enterLibId.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        enterLibId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterLibIdActionPerformed(evt);
            }
        });

        InsertButton4.setBackground(new java.awt.Color(102, 153, 255));
        InsertButton4.setText("Add to Cart");
        InsertButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButton4ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("SEARCH BOOK");

        lib_det.setLayout(new javax.swing.BoxLayout(lib_det, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout Enter1Layout = new javax.swing.GroupLayout(Enter1);
        Enter1.setLayout(Enter1Layout);
        Enter1Layout.setHorizontalGroup(
            Enter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Enter1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(enterLibId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(Enter1Layout.createSequentialGroup()
                .addGroup(Enter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Enter1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel6))
                    .addGroup(Enter1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(InsertButton4))
                    .addGroup(Enter1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lib_det, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Enter1Layout.setVerticalGroup(
            Enter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Enter1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(25, 25, 25)
                .addGroup(Enter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(enterLibId))
                .addGap(18, 18, 18)
                .addComponent(lib_det, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(InsertButton4)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout EnterLayout = new javax.swing.GroupLayout(Enter);
        Enter.setLayout(EnterLayout);
        EnterLayout.setHorizontalGroup(
            EnterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnterLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(Enter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        EnterLayout.setVerticalGroup(
            EnterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnterLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(Enter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        Panes.addTab("Search", Enter);

        Create.setBackground(new java.awt.Color(153, 255, 255));

        Create1.setBackground(new java.awt.Color(153, 255, 255));

        InsertButton1.setBackground(new java.awt.Color(102, 153, 255));
        InsertButton1.setText("SHOW ITEMS");
        InsertButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("CART ");

        jLabel4.setText("Ordered Books:");

        lib_det1.setLayout(new javax.swing.BoxLayout(lib_det1, javax.swing.BoxLayout.Y_AXIS));

        InsertButton2.setBackground(new java.awt.Color(102, 153, 255));
        InsertButton2.setText("CONFIRM ITEMS");
        InsertButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Create1Layout = new javax.swing.GroupLayout(Create1);
        Create1.setLayout(Create1Layout);
        Create1Layout.setHorizontalGroup(
            Create1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Create1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(InsertButton1)
                .addGap(45, 45, 45))
            .addGroup(Create1Layout.createSequentialGroup()
                .addGroup(Create1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Create1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel2))
                    .addGroup(Create1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(lib_det1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Create1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(InsertButton2)))
                .addGap(30, 70, Short.MAX_VALUE))
        );
        Create1Layout.setVerticalGroup(
            Create1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Create1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addGroup(Create1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(InsertButton1))
                .addGap(18, 18, 18)
                .addComponent(lib_det1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(InsertButton2)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout CreateLayout = new javax.swing.GroupLayout(Create);
        Create.setLayout(CreateLayout);
        CreateLayout.setHorizontalGroup(
            CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(Create1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        CreateLayout.setVerticalGroup(
            CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Create1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        Panes.addTab("Cart", Create);

        Create2.setBackground(new java.awt.Color(153, 255, 255));

        Create3.setBackground(new java.awt.Color(153, 255, 255));

        InsertButton5.setBackground(new java.awt.Color(102, 153, 255));
        InsertButton5.setText("CONFIRM BORROW");
        InsertButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButton5ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("DETAIL CONFIRMATION");

        jLabel8.setText("Already a Patron?");

        jLabel14.setText("Patron ID :");

        LibraryId4.setColumns(10);
        LibraryId4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        LibraryId4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibraryId4ActionPerformed(evt);
            }
        });

        jLabel9.setText("Not a Patron? Resgister here");

        jLabel19.setText("UserName :");

        LibraryName3.setColumns(10);

        jLabel20.setText("Password:");

        LibraryName4.setColumns(10);

        jLabel16.setText("Customer ID:");

        LibraryId5.setColumns(10);
        LibraryId5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        LibraryId5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibraryId5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Create3Layout = new javax.swing.GroupLayout(Create3);
        Create3.setLayout(Create3Layout);
        Create3Layout.setHorizontalGroup(
            Create3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Create3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(Create3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InsertButton5)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addGroup(Create3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(LibraryId4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Create3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(Create3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(Create3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(Create3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel19))))
                        .addGap(18, 18, 18)
                        .addGroup(Create3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LibraryName3)
                            .addComponent(LibraryName4)
                            .addComponent(LibraryId5))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Create3Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(39, 39, 39))
        );
        Create3Layout.setVerticalGroup(
            Create3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Create3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Create3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(LibraryId4))
                .addGap(14, 14, 14)
                .addComponent(jLabel9)
                .addGap(26, 26, 26)
                .addGroup(Create3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(LibraryId5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Create3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(LibraryName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Create3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(LibraryName4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(InsertButton5)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout Create2Layout = new javax.swing.GroupLayout(Create2);
        Create2.setLayout(Create2Layout);
        Create2Layout.setHorizontalGroup(
            Create2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Create2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(Create3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        Create2Layout.setVerticalGroup(
            Create2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Create2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(Create3, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        Panes.addTab("Details", Create2);

        Enter2.setBackground(new java.awt.Color(153, 255, 255));

        Enter3.setBackground(new java.awt.Color(153, 255, 255));

        jLabel28.setText("Patron ID :");

        enterLibId1.setColumns(10);
        enterLibId1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        enterLibId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterLibId1ActionPerformed(evt);
            }
        });

        InsertButton6.setBackground(new java.awt.Color(102, 153, 255));
        InsertButton6.setText("ENTER");
        InsertButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButton6ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setText("BORROWS");

        lib_det2.setLayout(new javax.swing.BoxLayout(lib_det2, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout Enter3Layout = new javax.swing.GroupLayout(Enter3);
        Enter3.setLayout(Enter3Layout);
        Enter3Layout.setHorizontalGroup(
            Enter3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Enter3Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(InsertButton6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Enter3Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(Enter3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lib_det2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Enter3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Enter3Layout.createSequentialGroup()
                            .addComponent(jLabel28)
                            .addGap(42, 42, 42)
                            .addComponent(enterLibId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Enter3Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(93, 93, 93)))))
        );
        Enter3Layout.setVerticalGroup(
            Enter3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Enter3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(Enter3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(enterLibId1))
                .addGap(18, 18, 18)
                .addComponent(InsertButton6)
                .addGap(33, 33, 33)
                .addComponent(lib_det2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout Enter2Layout = new javax.swing.GroupLayout(Enter2);
        Enter2.setLayout(Enter2Layout);
        Enter2Layout.setHorizontalGroup(
            Enter2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Enter2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(Enter3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        Enter2Layout.setVerticalGroup(
            Enter2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Enter2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Enter3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        Panes.addTab("Borrows", Enter2);

        Enter4.setBackground(new java.awt.Color(153, 255, 255));

        Enter5.setBackground(new java.awt.Color(153, 255, 255));

        jLabel29.setText("Patron ID :");

        enterLibId2.setColumns(10);
        enterLibId2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        enterLibId2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterLibId2ActionPerformed(evt);
            }
        });

        InsertButton7.setBackground(new java.awt.Color(102, 153, 255));
        InsertButton7.setText("ENTER");
        InsertButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButton7ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setText("RENEWAL");

        jButton1.setBackground(new java.awt.Color(102, 153, 255));
        jButton1.setText("RENEW");

        jLabel1.setText("Renew all selected?");

        javax.swing.GroupLayout Enter5Layout = new javax.swing.GroupLayout(Enter5);
        Enter5.setLayout(Enter5Layout);
        Enter5Layout.setHorizontalGroup(
            Enter5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Enter5Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(enterLibId2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Enter5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
            .addGroup(Enter5Layout.createSequentialGroup()
                .addGroup(Enter5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Enter5Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel11))
                    .addGroup(Enter5Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(InsertButton7))
                    .addGroup(Enter5Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Enter5Layout.setVerticalGroup(
            Enter5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Enter5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(Enter5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(enterLibId2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InsertButton7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(Enter5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout Enter4Layout = new javax.swing.GroupLayout(Enter4);
        Enter4.setLayout(Enter4Layout);
        Enter4Layout.setHorizontalGroup(
            Enter4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Enter4Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(Enter5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        Enter4Layout.setVerticalGroup(
            Enter4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Enter4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Enter5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        Panes.addTab("Renew", Enter4);

        Enter6.setBackground(new java.awt.Color(153, 255, 255));

        Enter7.setBackground(new java.awt.Color(153, 255, 255));

        jLabel30.setText("Patron ID :");

        enterLibId3.setColumns(10);
        enterLibId3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        enterLibId3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterLibId3ActionPerformed(evt);
            }
        });

        InsertButton8.setBackground(new java.awt.Color(102, 153, 255));
        InsertButton8.setText("ENTER");
        InsertButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButton8ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setText("RETURN BOOK");

        jButton2.setBackground(new java.awt.Color(102, 153, 255));
        jButton2.setText("RETURN");

        jLabel3.setText("Return all selected?");

        javax.swing.GroupLayout Enter7Layout = new javax.swing.GroupLayout(Enter7);
        Enter7.setLayout(Enter7Layout);
        Enter7Layout.setHorizontalGroup(
            Enter7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Enter7Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(enterLibId3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Enter7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
            .addGroup(Enter7Layout.createSequentialGroup()
                .addGroup(Enter7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Enter7Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel12))
                    .addGroup(Enter7Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(InsertButton8))
                    .addGroup(Enter7Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Enter7Layout.setVerticalGroup(
            Enter7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Enter7Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(Enter7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(enterLibId3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InsertButton8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(Enter7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton2))
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout Enter6Layout = new javax.swing.GroupLayout(Enter6);
        Enter6.setLayout(Enter6Layout);
        Enter6Layout.setHorizontalGroup(
            Enter6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Enter6Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(Enter7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        Enter6Layout.setVerticalGroup(
            Enter6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Enter6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Enter7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        Panes.addTab("Return", Enter6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Panes, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Panes, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void InsertButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButton4ActionPerformed
        lib_det.add(new Entry("B1", "The NameSake"));
        lib_det.add(new Entry("B2", "The Girl on the Train"));
        lib_det.add(new Entry("B3", "The Da Vinci Code"));
        lib_det.add(new Entry("B4", "The GoldFinch"));
        lib_det.add(new Entry("B5", "The Great Gatsby"));
    }//GEN-LAST:event_InsertButton4ActionPerformed

    private void enterLibIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterLibIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterLibIdActionPerformed

    private void InsertButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButton1ActionPerformed
        lib_det1.add(new Entry("B1", "The NameSake"));
        lib_det1.add(new Entry("B2", "The Girl on the Train"));
        lib_det1.add(new Entry("B3", "The Da Vinci Code"));
    }//GEN-LAST:event_InsertButton1ActionPerformed

    private void InsertButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertButton5ActionPerformed

    private void LibraryId4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibraryId4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LibraryId4ActionPerformed

    private void enterLibId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterLibId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterLibId1ActionPerformed

    private void InsertButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButton6ActionPerformed
        lib_det2.add(new Entry("B1", "The NameSake"));
        lib_det2.add(new Entry("B2", "The Girl on the Train"));
        lib_det2.add(new Entry("B3", "The Da Vinci Code"));
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertButton6ActionPerformed

    private void LibraryId5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibraryId5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LibraryId5ActionPerformed

    private void enterLibId2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterLibId2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterLibId2ActionPerformed

    private void InsertButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertButton7ActionPerformed

    private void enterLibId3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterLibId3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterLibId3ActionPerformed

    private void InsertButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertButton8ActionPerformed

    private void InsertButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButton2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Borrow Successful!");
    }//GEN-LAST:event_InsertButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Create;
    private javax.swing.JPanel Create1;
    private javax.swing.JPanel Create2;
    private javax.swing.JPanel Create3;
    private javax.swing.JPanel Enter;
    private javax.swing.JPanel Enter1;
    private javax.swing.JPanel Enter2;
    private javax.swing.JPanel Enter3;
    private javax.swing.JPanel Enter4;
    private javax.swing.JPanel Enter5;
    private javax.swing.JPanel Enter6;
    private javax.swing.JPanel Enter7;
    private javax.swing.JButton InsertButton1;
    private javax.swing.JButton InsertButton2;
    private javax.swing.JButton InsertButton4;
    private javax.swing.JButton InsertButton5;
    private javax.swing.JButton InsertButton6;
    private javax.swing.JButton InsertButton7;
    private javax.swing.JButton InsertButton8;
    private javax.swing.JTextField LibraryId4;
    private javax.swing.JTextField LibraryId5;
    private javax.swing.JTextField LibraryName3;
    private javax.swing.JTextField LibraryName4;
    private javax.swing.JTabbedPane Panes;
    private javax.swing.JTextField enterLibId;
    private javax.swing.JTextField enterLibId1;
    private javax.swing.JTextField enterLibId2;
    private javax.swing.JTextField enterLibId3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel lib_det;
    private javax.swing.JPanel lib_det1;
    private javax.swing.JPanel lib_det2;
    // End of variables declaration//GEN-END:variables
}

