/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package LMSMiniProject.TablePanels;

import javax.swing.JOptionPane;

/**
 *
 * @author Vijay Srinivas K
 */
public class CustomerPanel extends javax.swing.JPanel {

    /**
     * Creates new form LibraryPanel
     */
    public CustomerPanel() {
        initComponents();
        //setPreferredSize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Panes = new javax.swing.JTabbedPane();
        Create = new javax.swing.JPanel();
        Create3 = new javax.swing.JPanel();
        InsertButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        LibraryId4 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        LibraryName2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        LocId2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        YearEstd2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        YearEstd8 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        YearEstd9 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Update = new javax.swing.JPanel();
        Update1 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        LibraryId9 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        LibraryName5 = new javax.swing.JTextField();
        LocId5 = new javax.swing.JTextField();
        YearEstd10 = new javax.swing.JTextField();
        InsertButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        YearEstd11 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        YearEstd12 = new javax.swing.JTextField();
        Delete = new javax.swing.JPanel();
        Delete1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        LibraryId5 = new javax.swing.JTextField();
        InsertButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Purchase = new javax.swing.JPanel();
        Purchase1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        LocId3 = new javax.swing.JTextField();
        YearEstd3 = new javax.swing.JTextField();
        InsertButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 204, 204));

        Panes.setBackground(new java.awt.Color(102, 153, 255));
        Panes.setPreferredSize(new java.awt.Dimension(500, 500));

        Create.setBackground(new java.awt.Color(153, 255, 255));

        Create3.setBackground(new java.awt.Color(153, 255, 255));

        InsertButton4.setBackground(new java.awt.Color(102, 153, 255));
        InsertButton4.setText("PLACE ORDER");
        InsertButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButton4ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("DETAIL CONFIRMATION");

        jLabel8.setText("Already a customer?");

        jLabel14.setText("Customer ID :");

        LibraryId4.setColumns(10);
        LibraryId4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        LibraryId4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibraryId4ActionPerformed(evt);
            }
        });

        jLabel15.setText("First Name:");

        LibraryName2.setColumns(10);

        jLabel16.setText("Last Name:");

        LocId2.setColumns(10);

        jLabel17.setText("Date of Birth:");

        YearEstd2.setColumns(10);
        YearEstd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearEstd2ActionPerformed(evt);
            }
        });

        jLabel18.setText("Phone Number:");

        YearEstd8.setColumns(10);
        YearEstd8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearEstd8ActionPerformed(evt);
            }
        });

        jLabel33.setText("Email:");

        YearEstd9.setColumns(10);
        YearEstd9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearEstd9ActionPerformed(evt);
            }
        });

        jLabel9.setText("Not a customer? Resgister here");

        javax.swing.GroupLayout Create3Layout = new javax.swing.GroupLayout(Create3);
        Create3.setLayout(Create3Layout);
        Create3Layout.setHorizontalGroup(
            Create3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Create3Layout.createSequentialGroup()
                .addGroup(Create3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Create3Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(InsertButton4))
                    .addGroup(Create3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(Create3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Create3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LibraryName2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Create3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LocId2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Create3Layout.createSequentialGroup()
                                .addGroup(Create3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(Create3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(YearEstd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(YearEstd8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(Create3Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(YearEstd9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Create3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(Create3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addGroup(Create3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(34, 34, 34)
                                .addComponent(LibraryId4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Create3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(67, 67, 67))
        );
        Create3Layout.setVerticalGroup(
            Create3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Create3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Create3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(LibraryId4))
                .addGap(14, 14, 14)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Create3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(LibraryName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Create3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LocId2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Create3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YearEstd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Create3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(YearEstd8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Create3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YearEstd9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addGap(18, 18, 18)
                .addComponent(InsertButton4)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout CreateLayout = new javax.swing.GroupLayout(Create);
        Create.setLayout(CreateLayout);
        CreateLayout.setHorizontalGroup(
            CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Create3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        CreateLayout.setVerticalGroup(
            CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Create3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        Panes.addTab("Create", Create);

        Update.setBackground(new java.awt.Color(153, 255, 255));

        Update1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel34.setText("Customer ID :");

        LibraryId9.setColumns(10);
        LibraryId9.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        LibraryId9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibraryId9ActionPerformed(evt);
            }
        });

        jLabel35.setText("First Name:");

        jLabel36.setText("Last Name:");

        jLabel37.setText("Date of Birth:");

        jLabel38.setText("Phone Number:");

        LibraryName5.setColumns(10);

        LocId5.setColumns(10);

        YearEstd10.setColumns(10);
        YearEstd10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearEstd10ActionPerformed(evt);
            }
        });

        InsertButton6.setBackground(new java.awt.Color(102, 153, 255));
        InsertButton6.setText("Insert");
        InsertButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButton6ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("UPDATE CUSTOMER");

        YearEstd11.setColumns(10);
        YearEstd11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearEstd11ActionPerformed(evt);
            }
        });

        jLabel39.setText("Email:");

        YearEstd12.setColumns(10);
        YearEstd12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearEstd12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Update1Layout = new javax.swing.GroupLayout(Update1);
        Update1.setLayout(Update1Layout);
        Update1Layout.setHorizontalGroup(
            Update1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Update1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(Update1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addGroup(Update1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Update1Layout.createSequentialGroup()
                            .addComponent(jLabel35)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LibraryName5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Update1Layout.createSequentialGroup()
                            .addComponent(jLabel34)
                            .addGap(60, 60, 60)
                            .addComponent(LibraryId9))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Update1Layout.createSequentialGroup()
                            .addComponent(jLabel36)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LocId5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Update1Layout.createSequentialGroup()
                            .addGroup(Update1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel37)
                                .addComponent(jLabel38)
                                .addComponent(jLabel39))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(Update1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(YearEstd10)
                                .addComponent(YearEstd11)
                                .addComponent(YearEstd12)))))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Update1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(InsertButton6)
                .addGap(111, 111, 111))
        );
        Update1Layout.setVerticalGroup(
            Update1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Update1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addGap(35, 35, 35)
                .addGroup(Update1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(LibraryId9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Update1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(LibraryName5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Update1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LocId5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Update1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YearEstd10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Update1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(YearEstd11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Update1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YearEstd12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addGap(28, 28, 28)
                .addComponent(InsertButton6)
                .addContainerGap())
        );

        javax.swing.GroupLayout UpdateLayout = new javax.swing.GroupLayout(Update);
        Update.setLayout(UpdateLayout);
        UpdateLayout.setHorizontalGroup(
            UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(Update1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        UpdateLayout.setVerticalGroup(
            UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Update1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        Panes.addTab("Update", Update);

        Delete.setBackground(new java.awt.Color(153, 255, 255));

        Delete1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel19.setText("Customer ID:");

        LibraryId5.setColumns(10);
        LibraryId5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        LibraryId5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibraryId5ActionPerformed(evt);
            }
        });

        InsertButton2.setBackground(new java.awt.Color(102, 153, 255));
        InsertButton2.setText("Delete");
        InsertButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("DELETE CUSTOMER");

        javax.swing.GroupLayout Delete1Layout = new javax.swing.GroupLayout(Delete1);
        Delete1.setLayout(Delete1Layout);
        Delete1Layout.setHorizontalGroup(
            Delete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Delete1Layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(InsertButton2)
                .addGap(106, 106, 106))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Delete1Layout.createSequentialGroup()
                .addGroup(Delete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Delete1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(Delete1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LibraryId5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        Delete1Layout.setVerticalGroup(
            Delete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Delete1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel4)
                .addGap(41, 41, 41)
                .addGroup(Delete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(LibraryId5))
                .addGap(40, 40, 40)
                .addComponent(InsertButton2)
                .addGap(104, 104, 104))
        );

        javax.swing.GroupLayout DeleteLayout = new javax.swing.GroupLayout(Delete);
        Delete.setLayout(DeleteLayout);
        DeleteLayout.setHorizontalGroup(
            DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeleteLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(Delete1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        DeleteLayout.setVerticalGroup(
            DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Delete1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        Panes.addTab("Delete", Delete);

        Purchase.setBackground(new java.awt.Color(153, 255, 255));

        Purchase1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel22.setText("Book IDs:");

        jLabel23.setText("Quantities:");

        LocId3.setColumns(10);

        YearEstd3.setColumns(10);
        YearEstd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearEstd3ActionPerformed(evt);
            }
        });

        InsertButton3.setBackground(new java.awt.Color(102, 153, 255));
        InsertButton3.setText("PURCHASE");
        InsertButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButton3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("PURCHASE BOOK");

        javax.swing.GroupLayout Purchase1Layout = new javax.swing.GroupLayout(Purchase1);
        Purchase1.setLayout(Purchase1Layout);
        Purchase1Layout.setHorizontalGroup(
            Purchase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Purchase1Layout.createSequentialGroup()
                .addGroup(Purchase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Purchase1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(Purchase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Purchase1Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LocId3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Purchase1Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(YearEstd3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Purchase1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel5))))
                    .addGroup(Purchase1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(InsertButton3)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        Purchase1Layout.setVerticalGroup(
            Purchase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Purchase1Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(34, 34, 34)
                .addGroup(Purchase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LocId3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Purchase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YearEstd3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(35, 35, 35)
                .addComponent(InsertButton3)
                .addGap(88, 88, 88))
        );

        javax.swing.GroupLayout PurchaseLayout = new javax.swing.GroupLayout(Purchase);
        Purchase.setLayout(PurchaseLayout);
        PurchaseLayout.setHorizontalGroup(
            PurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PurchaseLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(Purchase1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        PurchaseLayout.setVerticalGroup(
            PurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PurchaseLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Purchase1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        Panes.addTab("Purchase Book", Purchase);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Panes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Panes, javax.swing.GroupLayout.PREFERRED_SIZE, 485, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LibraryId5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibraryId5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LibraryId5ActionPerformed

    private void InsertButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertButton2ActionPerformed

    private void YearEstd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearEstd3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YearEstd3ActionPerformed

    private void InsertButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButton3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Book Not Found");
    }//GEN-LAST:event_InsertButton3ActionPerformed

    private void LibraryId9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibraryId9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LibraryId9ActionPerformed

    private void YearEstd10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearEstd10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YearEstd10ActionPerformed

    private void InsertButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertButton6ActionPerformed

    private void YearEstd11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearEstd11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YearEstd11ActionPerformed

    private void YearEstd12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearEstd12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YearEstd12ActionPerformed

    private void InsertButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertButton4ActionPerformed

    private void LibraryId4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibraryId4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LibraryId4ActionPerformed

    private void YearEstd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearEstd2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YearEstd2ActionPerformed

    private void YearEstd8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearEstd8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YearEstd8ActionPerformed

    private void YearEstd9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearEstd9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YearEstd9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Create;
    private javax.swing.JPanel Create3;
    private javax.swing.JPanel Delete;
    private javax.swing.JPanel Delete1;
    private javax.swing.JButton InsertButton2;
    private javax.swing.JButton InsertButton3;
    private javax.swing.JButton InsertButton4;
    private javax.swing.JButton InsertButton6;
    private javax.swing.JTextField LibraryId4;
    private javax.swing.JTextField LibraryId5;
    private javax.swing.JTextField LibraryId9;
    private javax.swing.JTextField LibraryName2;
    private javax.swing.JTextField LibraryName5;
    private javax.swing.JTextField LocId2;
    private javax.swing.JTextField LocId3;
    private javax.swing.JTextField LocId5;
    private javax.swing.JTabbedPane Panes;
    private javax.swing.JPanel Purchase;
    private javax.swing.JPanel Purchase1;
    private javax.swing.JPanel Update;
    private javax.swing.JPanel Update1;
    private javax.swing.JTextField YearEstd10;
    private javax.swing.JTextField YearEstd11;
    private javax.swing.JTextField YearEstd12;
    private javax.swing.JTextField YearEstd2;
    private javax.swing.JTextField YearEstd3;
    private javax.swing.JTextField YearEstd8;
    private javax.swing.JTextField YearEstd9;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}

