/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package LMSMiniProject.TablePanels;

import LMSMiniProject.DbConnection;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Vijay Srinivas K
 */
public class LibraryPanel extends javax.swing.JPanel {
    private Connection con;
    private Statement st;
    private PreparedStatement ps;
    private ResultSet rs;
    private String library_id;
    /**
     * Creates new form LibraryPanel
     */
    public LibraryPanel(String library_id) {
        initComponents();
        this.library_id = library_id;
        try {
            con = DbConnection.getConnection();
        }
        catch (SQLException | ClassNotFoundException ignore) {
        }
        //setPreferredSize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Panes = new javax.swing.JTabbedPane();
        Create = new javax.swing.JPanel();
        Create1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        libName = new javax.swing.JTextField();
        locId = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        rating = new javax.swing.JSlider();
        InsertButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pat_det = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lib_det = new javax.swing.JPanel();
        Delete = new javax.swing.JPanel();
        Delete1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        delLibId = new javax.swing.JTextField();
        InsertButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        AddBookInfo = new javax.swing.JPanel();
        AddBookInfo1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        isbn = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        InsertButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        Update = new javax.swing.JPanel();
        Update1 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        updateLibId = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        updateLibName = new javax.swing.JTextField();
        updateLocId = new javax.swing.JTextField();
        updateYear = new javax.swing.JTextField();
        updateRating = new javax.swing.JSlider();
        InsertButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 204, 204));

        Panes.setBackground(new java.awt.Color(102, 153, 255));
        Panes.setPreferredSize(new java.awt.Dimension(500, 500));

        Create.setBackground(new java.awt.Color(153, 255, 255));

        Create1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel15.setText("Library Name :");

        jLabel16.setText("Location ID : ");

        jLabel17.setText("Year Established :");

        jLabel18.setText("Rating : ");

        libName.setColumns(10);

        locId.setColumns(10);

        year.setColumns(10);
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });

        rating.setMajorTickSpacing(1);
        rating.setMaximum(5);
        rating.setPaintLabels(true);

        InsertButton1.setBackground(new java.awt.Color(102, 153, 255));
        InsertButton1.setText("Display");
        InsertButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Create1Layout = new javax.swing.GroupLayout(Create1);
        Create1.setLayout(Create1Layout);
        Create1Layout.setHorizontalGroup(
            Create1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Create1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(Create1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Create1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(libName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Create1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(locId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Create1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(74, 74, 74)
                        .addComponent(rating, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(Create1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Create1Layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(InsertButton1)
                .addGap(110, 110, 110))
        );
        Create1Layout.setVerticalGroup(
            Create1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Create1Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(Create1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(libName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Create1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Create1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Create1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(rating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(InsertButton1)
                .addGap(23, 23, 23))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("DISPLAY INFORMATION");

        pat_det.setLayout(new javax.swing.BoxLayout(pat_det, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pat_det);

        lib_det.setLayout(new javax.swing.BoxLayout(lib_det, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane3.setViewportView(lib_det);

        javax.swing.GroupLayout CreateLayout = new javax.swing.GroupLayout(Create);
        Create.setLayout(CreateLayout);
        CreateLayout.setHorizontalGroup(
            CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(Create1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(115, 115, 115))
        );
        CreateLayout.setVerticalGroup(
            CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGroup(CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(CreateLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(Create1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CreateLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );

        Panes.addTab("Create", Create);

        Delete.setBackground(new java.awt.Color(153, 255, 255));

        Delete1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel19.setText("Library ID :");

        delLibId.setColumns(10);
        delLibId.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        delLibId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delLibIdActionPerformed(evt);
            }
        });

        InsertButton2.setBackground(new java.awt.Color(102, 153, 255));
        InsertButton2.setText("Delete");
        InsertButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("DELETE LIBRARY");

        javax.swing.GroupLayout Delete1Layout = new javax.swing.GroupLayout(Delete1);
        Delete1.setLayout(Delete1Layout);
        Delete1Layout.setHorizontalGroup(
            Delete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Delete1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(delLibId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Delete1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Delete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Delete1Layout.createSequentialGroup()
                        .addComponent(InsertButton2)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Delete1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(46, 46, 46))))
        );
        Delete1Layout.setVerticalGroup(
            Delete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Delete1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel4)
                .addGap(41, 41, 41)
                .addGroup(Delete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(delLibId))
                .addGap(40, 40, 40)
                .addComponent(InsertButton2)
                .addGap(104, 104, 104))
        );

        javax.swing.GroupLayout DeleteLayout = new javax.swing.GroupLayout(Delete);
        Delete.setLayout(DeleteLayout);
        DeleteLayout.setHorizontalGroup(
            DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeleteLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(Delete1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        DeleteLayout.setVerticalGroup(
            DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Delete1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        Panes.addTab("Delete", Delete);

        AddBookInfo.setBackground(new java.awt.Color(153, 255, 255));

        AddBookInfo1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel22.setText("ISBN:");

        jLabel23.setText("Quantity");

        jLabel24.setText("Price:");

        isbn.setColumns(10);

        quantity.setColumns(10);
        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });

        InsertButton3.setBackground(new java.awt.Color(102, 153, 255));
        InsertButton3.setText("Insert");
        InsertButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButton3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("ADD BOOK");

        price.setColumns(10);
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddBookInfo1Layout = new javax.swing.GroupLayout(AddBookInfo1);
        AddBookInfo1.setLayout(AddBookInfo1Layout);
        AddBookInfo1Layout.setHorizontalGroup(
            AddBookInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddBookInfo1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(InsertButton3)
                .addGap(113, 113, 113))
            .addGroup(AddBookInfo1Layout.createSequentialGroup()
                .addGroup(AddBookInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddBookInfo1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(AddBookInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddBookInfo1Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(isbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddBookInfo1Layout.createSequentialGroup()
                                .addGroup(AddBookInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(AddBookInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(price)
                                    .addComponent(quantity)))))
                    .addGroup(AddBookInfo1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel5)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        AddBookInfo1Layout.setVerticalGroup(
            AddBookInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddBookInfo1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(AddBookInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddBookInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddBookInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addComponent(InsertButton3)
                .addContainerGap())
        );

        javax.swing.GroupLayout AddBookInfoLayout = new javax.swing.GroupLayout(AddBookInfo);
        AddBookInfo.setLayout(AddBookInfoLayout);
        AddBookInfoLayout.setHorizontalGroup(
            AddBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddBookInfoLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(AddBookInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        AddBookInfoLayout.setVerticalGroup(
            AddBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddBookInfoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(AddBookInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        Panes.addTab("Add Book", AddBookInfo);

        Update.setBackground(new java.awt.Color(153, 255, 255));

        Update1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel28.setText("Library ID :");

        updateLibId.setColumns(10);
        updateLibId.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        updateLibId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateLibIdActionPerformed(evt);
            }
        });

        jLabel29.setText("Library Name :");

        jLabel30.setText("Location ID : ");

        jLabel31.setText("Year Established :");

        jLabel32.setText("Rating : ");

        updateLibName.setColumns(10);

        updateLocId.setColumns(10);

        updateYear.setColumns(10);
        updateYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateYearActionPerformed(evt);
            }
        });

        updateRating.setMajorTickSpacing(1);
        updateRating.setMaximum(5);
        updateRating.setPaintLabels(true);

        InsertButton5.setBackground(new java.awt.Color(102, 153, 255));
        InsertButton5.setText("Insert");
        InsertButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButton5ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("UPDATE LIBRARY");

        javax.swing.GroupLayout Update1Layout = new javax.swing.GroupLayout(Update1);
        Update1.setLayout(Update1Layout);
        Update1Layout.setHorizontalGroup(
            Update1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Update1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(Update1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Update1Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateLibName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Update1Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(60, 60, 60)
                        .addComponent(updateLibId))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Update1Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateLocId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Update1Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addGap(74, 74, 74)
                        .addComponent(updateRating, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(Update1Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Update1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Update1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Update1Layout.createSequentialGroup()
                        .addComponent(InsertButton5)
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Update1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(59, 59, 59))))
        );
        Update1Layout.setVerticalGroup(
            Update1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Update1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(35, 35, 35)
                .addGroup(Update1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(updateLibId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Update1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(updateLibName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Update1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateLocId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Update1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Update1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(updateRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(InsertButton5)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout UpdateLayout = new javax.swing.GroupLayout(Update);
        Update.setLayout(UpdateLayout);
        UpdateLayout.setHorizontalGroup(
            UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(Update1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        UpdateLayout.setVerticalGroup(
            UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Update1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        Panes.addTab("Update", Update);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Panes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Panes, javax.swing.GroupLayout.PREFERRED_SIZE, 485, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void InsertButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertButton5ActionPerformed

    private void updateYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateYearActionPerformed

    private void updateLibIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateLibIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateLibIdActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void InsertButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButton3ActionPerformed
        for (int i = 0; i < Integer.parseInt(quantity.getText()); i++) {
        String query = "SELECT book_id FROM book WHERE library_id = '" + library_id + "'";
        int newId = 0;
        int prevId = 0;
        int finalId = 0;
        boolean chk = false;
        
        try {
            st = con.createStatement();
            rs = st.executeQuery(query);
            
            if(rs.next())
                prevId = Integer.parseInt(rs.getString(1).substring(1));
            
            while ((chk = rs.next())) {
                newId = Integer.parseInt(rs.getString(1).substring(1));
                System.out.println(prevId + " " + newId);
                if (newId - prevId > 1) {
                    finalId = prevId + 1;
                    break;
                }
                prevId = newId;
            }
            
            if (chk == false)
                finalId = newId + 1;
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
        
        System.out.println(finalId);
        String bookid = Integer.toString(finalId);
        
        if (bookid.length() == 1) {
            bookid = "B00" + bookid;
        }
        else {
            bookid = "B0" + bookid;
        }
        
        System.out.println(bookid);
        String query2 = "INSERT INTO book VALUES(?, ?, ?, ?, ?)";
        try {
            ps = con.prepareStatement(query2);
            ps.setString(1, bookid);
            ps.setString(2, library_id);
            ps.setString(3, isbn.getText());
            ps.setFloat(4, Float.parseFloat(price.getText()));
            ps.setInt(5, 1);
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Inserted book");
        }
        catch (SQLException ex) {
            Logger.getLogger(LibraryPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid input present in form.");
        }
        }
    }//GEN-LAST:event_InsertButton3ActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void InsertButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButton2ActionPerformed
        String query = "DELETE FROM library WHERE library_id = '" + delLibId.getText() + "'";
        try {
            st = con.createStatement();
            rs = st.executeQuery(query);

            if (rs.next())
            JOptionPane.showMessageDialog(this, "Library Deleted");
            else
            JOptionPane.showMessageDialog(this, "Library Does not exist");
        }
        catch(SQLException ex) {
            Logger.getLogger(LibraryPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_InsertButton2ActionPerformed

    private void delLibIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delLibIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delLibIdActionPerformed

    private void InsertButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButton1ActionPerformed
        
        String query1 = "SELECT * FROM library WHERE library_id = '" + library_id + "'";
        String query2 = "SELECT b.book_id, bd.title FROM book b, book_details bd WHERE b.isbn = bd.isbn AND b.availible = 1 AND b.library_id = '" + library_id + "' ORDER BY book_id";
        String query3 = "SELECT p.patron_id, c.cust_fn, c.cust_ln FROM patron p, customer c WHERE p.cust_id = c.cust_id AND library_id = '" + library_id + "'";

        try {
            st = con.createStatement();
            rs = st.executeQuery(query1);

            rs.next();

            libName.setText(rs.getString(2));
            locId.setText(rs.getString(3));
            year.setText(rs.getString(4));
            rating.setValue(Integer.parseInt(rs.getString(4)));

            st = con.createStatement();
            rs = st.executeQuery(query2);

            while(rs.next()) {
                lib_det.add(new Entry(rs.getString(1), rs.getString(2)));
            }
            lib_det.repaint();
            lib_det.revalidate();

            st = con.createStatement();
            rs = st.executeQuery(query3);

            while(rs.next()) {
                pat_det.add(new Entry(rs.getString(1), rs.getString(2)));
            }
            pat_det.repaint();
            pat_det.revalidate();

        }
        catch (SQLException ex) {

            Logger.getLogger(LibraryPanel.class.getName()).log(Level.SEVERE, null, ex);

            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this, "Invalid input present in form.");
        }
    }//GEN-LAST:event_InsertButton1ActionPerformed

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddBookInfo;
    private javax.swing.JPanel AddBookInfo1;
    private javax.swing.JPanel Create;
    private javax.swing.JPanel Create1;
    private javax.swing.JPanel Delete;
    private javax.swing.JPanel Delete1;
    private javax.swing.JButton InsertButton1;
    private javax.swing.JButton InsertButton2;
    private javax.swing.JButton InsertButton3;
    private javax.swing.JButton InsertButton5;
    private javax.swing.JTabbedPane Panes;
    private javax.swing.JPanel Update;
    private javax.swing.JPanel Update1;
    private javax.swing.JTextField delLibId;
    private javax.swing.JTextField isbn;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField libName;
    private javax.swing.JPanel lib_det;
    private javax.swing.JTextField locId;
    private javax.swing.JPanel pat_det;
    private javax.swing.JTextField price;
    private javax.swing.JTextField quantity;
    private javax.swing.JSlider rating;
    private javax.swing.JTextField updateLibId;
    private javax.swing.JTextField updateLibName;
    private javax.swing.JTextField updateLocId;
    private javax.swing.JSlider updateRating;
    private javax.swing.JTextField updateYear;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}

